name: onnx-example

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow~=2.15.0
      - pillow>=10.3.0
      - tf2onnx~=1.16.0
      - onnxruntime~=1.16.3
