# https://taskfile.dev

version: 3

vars:
  py_version: 3.10
  env_name: onnx-example

tasks:
  default:
    desc: List all tasks
    cmd: task --list-all

  conda:
    desc: Setup conda environment
    cmds:
      - conda create -n {{ .env_name }} python={{ .py_version }} -y
      - conda run -n {{ .env_name }} --live-stream python -m pip install -r requirements.txt

  train:
    desc: Train MNIST model and convert to ONNX format
    cmds:
      - conda run -n {{ .env_name }} --live-stream python train.py
      - conda run -n {{ .env_name }} --live-stream python -m tf2onnx.convert --saved-model ./saved_model --output ./model.onnx

  build:
    desc: Build C project
    cmds:
      - cmake -B ./cmake-build-debug -S .
      - cmake --build ./cmake-build-debug --target onnx_inference_example

  run:
    desc: Run executable
    cmd: ./cmake-build-debug/onnx_inference_example
